version: '3.5'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"

  athleteeventapi:
    image: athleteeventapi
    ports:
      - "9013:80"
    environment:
      DatabaseConnection: "mongodb://db:27017"
      DatabaseName: "AthleteEventSbaDb"
    depends_on:
      - db