version: '3.5'
services:
  sqldb:
    image: mcr.microsoft.com/mssql/server
    ports:
      - '1433:1433'
    environment:
      SA_PASSWORD: "Passw0rd123"
      ACCEPT_EULA: "Y"

  bookingapi:
    image: bookingapi
    ports:
      - '9014:80'
    environment:
      DataConnection: "Data Source=sqldb;Initial Catalog=BookingSbaDb;User Id=sa;Password=Passw0rd123;MultipleActiveResultSets=True;Persist Security Info=True"
    depends_on:
      - sqldb